- hosts: all
  become: yes
  tasks:
    - name: Pull Docker image
      docker_container:
        name: task-tracker
        image: your_dockerhub/task-tracker:latest
        state: started
        restart_policy: always
        ports:
          - "3000:3000"
